#!/bin/bash
str1="$1"
str2="$2"


[[ "$str1" == "$str2" ]] && echo "Equal"
[[ "$str1" != "$str2" ]] && echo "Not equal"
[[ -z "$str1" && -z "$str2" ]] && echo "Both argumenst are empty" || [[ -z "$str2" ]] && echo "second argument is empty"

